# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e31808407387dde9bf57bfa37f192bf93674107a4031daaa5e07d0692a7a2a8b0a901187ee3c19062052aa5db253e03e1a78e6f1a2d6d845f02c63b10da2a7e

test:
  secret_key_base: 01f3a49ddaf6b0bffa100bab354f050987c374b8e5f430276bfba38c8615d4ad0b302f9cff65948e5f26c81f65799326dbf4b320743c92ea9bacf595f77698a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
